# Generated by Django 5.2 on 2025-04-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='img_profile',
            field=models.ImageField(blank=True, null=True, upload_to='ImagenesPerfil'),
        ),
    ]
