# Generated by Django 5.2 on 2025-06-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_img_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='img_profile',
            field=models.ImageField(default='profile_pics/default-avatar-profile.jpg', upload_to='profile_pics/'),
        ),
    ]
