# Generated by Django 5.2 on 2025-06-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_options_alter_usuario_img_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='img_profile',
            field=models.ImageField(default='default-avatar-profile.jpg', upload_to=''),
        ),
    ]
